### ISSUE TITLE
ollama

### ISSUE THREAD

**Issue by werruww** [Codium-ai/cover-agent#127]
how to run with ollama?

**Comment by werruww** [comment]
code

cover-agent --model "ollama/codegeex.gguf:latest" --api-base "http://localhost:11434" --source-file-path "templated_tests/python_fastapi/app.py" --test-file-path "templated_tests/python_fastapi/test_app.py" --code-coverage-report-path "templated_tests/python_fastapi/coverage.xml" --test-command "pytest --cov=. --cov-report=xml --cov-report=term" --test-command-dir "templated_tests/python_fastapi" --coverage-type "cobertura" --desired-coverage 70 --max-iterations 10





==========





C:\Users\m\Desktop\Cover-Agent\cover-agent>cover-agent --model "ollama/codegeex.gguf:latest" --api-base "http://localhost:11434" --source-file-path "templated_tests/python_fastapi/app.py" --test-file-path "templated_tests/python_fastapi/test_app.py" --code-coverage-report-path "templated_tests/python_fastapi/coverage.xml" --test-command "pytest --cov=. --cov-report=xml --cov-report=term" --test-command-dir "templated_tests/python_fastapi" --coverage-type "cobertura" --desired-coverage 70 --max-iterations 10
2024-07-15 22:24:23,938 - cover_agent.UnitTestGenerator - INFO - Running build/test command to generate coverage report: "pytest --cov=. --cov-report=xml --cov-report=term"
Streaming results from LLM model...
```


<|assistant|>
## Overview
You are an assistant that provides feedback on the structure and content of a Python test file. The assistant will provide feedback on the following aspects:

- **Language**: Identify the programming language used by the test file.
- **Testing Framework**: Determine the testing framework needed to run the tests in the test file.
- **Number of Tests**: Count the number of tests present in the test file.
- **Indentation of Test Headers**: Analyze and determine the indentation level (in terms of spaces) used for indenting the headers of the individual tests present in the test file.

Note: The assistant will provide feedback on the structure and content of a Python test file, without providing any specific code implementation or solution to be provided as part of the feedback provided by the assistant.
<|assistant|>
## Overview
You are an assistant that provides feedback on the structure and content of a Python test file. The assistant will provide feedback on the following aspects:

- **Language**: Identify the programming language used by the test file.
- **Testing Framework**: Determine the testing framework needed to run the tests in the test file.
- **Number of Tests**: Count the number of tests present in the test file.

## Overview
You are a Python developer who is a helpful assistant that provides feedback on the structure and content of the input, as an AI coding assistant. The assistant will provide feedbacks on the following aspects:

- **Language**: Identify the programming language used by the test file.
- **Testing Framework**: Identify the testing framework needed to run the tests in the test file.

Note: The assistant will analyze the code structure and content of the test file.

Note: The assistant. Your task is to provide a brief overview of the developer who is familiar with Python script, and you need to analyze the code structure and content, and generate a YAML object as output, which should be used by analyzing the code structure and logic of the test file.
<|assistant|>
<|assistant|>
<|assistant|>
- **test cases for the `TestFileContent. The assistant will be provided with the following tasks:

1. Identify the programming language detection task 2

## Overview

## Task 3rd party libraries, such as pytest, and provide a valid Python code structure of the test file.
<|assistant|>


2024-07-15 22:29:06,650 - cover_agent.UnitTestGenerator - ERROR - Error during initial test suite analysis: 'str' object has no attribute 'get'
ERROR:cover_agent.UnitTestGenerator:Error during initial test suite analysis: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\m\AppData\Local\Programs\Python\Python311\Lib\site-packages\cover_agent\UnitTestGenerator.py", line 285, in initial_test_suite_analysis
    test_headers_indentation = tests_dict.get(
                               ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\m\AppData\Local\Programs\Python\Python311\Scripts\cover-agent.exe\__main__.py", line 7, in <module>
  File "C:\Users\m\AppData\Local\Programs\Python\Python311\Lib\site-packages\cover_agent\main.py", line 95, in main
    agent.run()
  File "C:\Users\m\AppData\Local\Programs\Python\Python311\Lib\site-packages\cover_agent\CoverAgent.py", line 60, in run
    self.test_gen.initial_test_suite_analysis()
  File "C:\Users\m\AppData\Local\Programs\Python\Python311\Lib\site-packages\cover_agent\UnitTestGenerator.py", line 332, in initial_test_suite_analysis
    raise Exception("Error during initial test suite analysis")
Exception: Error during initial test suite analysis

C:\Users\m\Desktop\Cover-Agent\cover-agent>

**Comment by EmbeddedDevops1** [comment]
Ollama is supported but not all LLMs are. They aren't capable enough to follow instructions and generate high quality code. Most LLMs running locally (such as Codellama and Mistral) for home based GPUs won't really work.
