### ISSUE TITLE
 cover-agent still requires OPENAI_API_KEY even after fixing #15

### ISSUE THREAD

**Issue by gklein** [Codium-ai/cover-agent#25]
```
 git --no-pager show HEAD            
commit e9654cc76271086f3198a7dfba604beddc0f11fd (HEAD -> main, origin/main, origin/HEAD)
Merge: 71cf0df 20c7c5f
Author: Tal <talrid@gmail.com>
Date:   Wed May 22 10:06:32 2024 +0300

    Merge pull request #24 from Codium-ai/15-feature-request-support-locally-running-llm
    
    Moving to LiteLLM with env var approach. Closes #15.


poetry run cover-agent \
  --source-file-path "templated_tests/python_fastapi/app.py" \
  --test-file-path "templated_tests/python_fastapi/test_app.py" \
  --code-coverage-report-path "templated_tests/python_fastapi/coverage.xml" \
  --test-command "pytest --cov=. --cov-report=xml --cov-report=term" \
  --test-command-dir "templated_tests/python_fastapi" \
  --coverage-type "cobertura" \
  --desired-coverage 70 \
  --max-iterations 10           
2024-05-22 11:24:43,285 - cover_agent.UnitTestGenerator - INFO - Running initial build/test command to generate coverage report: "pytest --cov=. --cov-report=xml --cov-report=term"
2024-05-22 11:24:44,847 - cover_agent.main - INFO - Current Coverage: 60.47%
2024-05-22 11:24:44,847 - cover_agent.main - INFO - Desired Coverage: 70%

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/cover-agent-faactadJ-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 574, in completion
    raise e
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/cover-agent-faactadJ-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 492, in completion
    return self.streaming(
           ^^^^^^^^^^^^^^^
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/cover-agent-faactadJ-py3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 654, in streaming
    openai_client = OpenAI(
                    ^^^^^^^
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/cover-agent-faactadJ-py3.11/lib/python3.11/site-packages/openai/_client.py", line 104, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

**Comment by mrT23** [comment]
@gklein i dont understand. Which model are you trying to use ?

You need some model. the default is openai
