### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by gklein** [Codium-ai/cover-agent#58]
I've got this failure after running a large number of iterations using --model ollama/codeqwen:chat 

2024-05-28 08:38:28,905 - cover_agent.UnitTestGenerator - INFO - Total token used count for LLM model ollama/codeqwen:chat: 2475
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/cover-agent/cover_agent/main.py", line 170, in main
    test_result = test_gen.validate_test(generated_test, generated_tests_dict)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/cover-agent/cover_agent/UnitTestGenerator.py", line 285, in validate_test
    delta_indent = needed_indent - initial_indent
                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'

**Comment by mrT23** [comment]
Thanks, will review

**Comment by mrT23** [comment]
try main again.
i tested it, and it works with

ollama/llama3
ollama/lama3:70b
ollama/codeqwen:v1.5
